### ISSUE TITLE
Authenticate Login

### ISSUE THREAD

**Issue by NonsoEz** [NonsoEz/Team-Bleau#3]

**Comment by lord-tx** [comment]
Guidelines for efficiency:

NB: This is just a way of doing things, not explicit rules.

We would work on the authentication in three phases:

1. Initial code development (Procedural);
	This could be simple or complex code that runs without
	error, giving variable names that are easy to decipher.
	commenting early and necessarily.

2. Optimizaition and tweaking:
	In this part, we would take some time to go throught the
	code and see how we can add some things and make it secure
	and/or run faster.

3. Finalizing and deploying:
	After all team members are satisfied with the code base,
	we can officially say we are done and test it a little 
	before deployment.

This is a pretty straighforward authentication apart from the key
generation with GoogleAuth. I'd love it if we can all take some time
out and add to the repository.

I'd start with a simple page and authentication I re-drafted to work
with mySQL but we'll change it to work with a JSON.

**Comment by tolu-six** [comment]
Signup.php file has been committed.
